# Generated by Django 5.0.1 on 2024-02-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
